CONTAINER BJS_Camera_Tag
{
    NAME BJS_Camera_Tag;
        
    GROUP BJS_CAMERA_SETTINGS
    {
        BOOL BJS_CAMERA_MAKE_DEFAULT {}
        BOOL BJS_CAMERA_ATTACH_CONTROLS {}
        REAL BJS_CAMERA_SPEED {MIN 0.01;}
        REAL BJS_CAMERA_ANGULAR_SENSIBILITY{MIN 0.01;}
        VECTOR BJS_CAMERA_Z_CLIP {}
    }
}